apiVersion: ENC[AES256_GCM,data:I+A=,iv:uT0TsDQ12VBkgzbjrqXOFFfK4YEWTUkVXDgAQldViuo=,tag:hCztakvxbK5QJQqwGgznhg==,type:str]
kind: ENC[AES256_GCM,data:qFX+E14y,iv:nvfwvds+5XjyyWWzwaHn7/kHx0SPjdmX3SpG/cMpdo0=,tag:XX8Zuowdjgyx5nJYGDuBsQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:X27yKNYCCN3ZtugRStpT,iv:q/H758xKNxeQq6PEHv0sKkpZ0H8FM1GfljEQwmkk2SY=,tag:6DDkUzwMFiFnQZz0yGQYWg==,type:str]
type: ENC[AES256_GCM,data:En5YtjI1,iv:YjqnQdhEhDD1QSDfVSsvoD7ChMcdIDx+a2cEC59iTPw=,tag:bPTI1qW8XdmqCRT8kaeNig==,type:str]
stringData:
    user: ENC[AES256_GCM,data:SjZHW37oYg==,iv:c95m/rF85Bv9LLSYndIhn464UdrYHgcIhNw+fnurfoY=,tag:ExLDW26mlz2pNuqcE69YqQ==,type:str]
    dbname: ENC[AES256_GCM,data:tEftQxZ8Qw==,iv:p1E41tpenSOLJtBVJ/wqHSn6kDOxnstp9Q7YmGPjx9s=,tag:rTf7r93MowxEdzoTfnh5vA==,type:str]
    password: ENC[AES256_GCM,data:LGIYf24ZTLQfSgmdiSEblQzrTOi72c9fdQGsqYPPFy4ZO3QJ5wbJgj5kBG7Gw3e0NdgFsKe1/VE/VHN93pMQzA==,iv:ZSr+5PRUkhJlijvADPdukyVDb1w0PLgV7gl5b6wRyVo=,tag:CQcpGbJJNuZqiBt832V9ww==,type:str]
sops:
    age:
        - recipient: age1hj83fz2clp28q9sylkdpn50agz5z650nncl2c5g2xwgm6g6vxexqdjdecn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYkcyUmo2TlhtWkw1NFgy
            S091SlRYay81ZlRtVGljaGlSdXB4Q1Y3cWpZCmRyTm16Nm5FbmhZdndDMEFVcDBY
            QmdyLzQ5VE9UOWtFUHpYM24vQTlYSVUKLS0tIHN1YWQrN0U1UUhYM0k5bDQzRmJp
            U0hZTFZaWFVOZ2svSm1VVUZPQk1xcE0KqNmgioARKanO+hmTuQEzqgta6k3hm9Wx
            5IAH1jfT5e+qvCLbWBA3jugG1DAtGhn8JttTOwUIhBHN+e3LaoUeqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T12:42:26Z"
    mac: ENC[AES256_GCM,data:TOnOopVKhqEH3SIz1gTIQG95acTVKiClLrdqFtf1+HMEoTLZcuYrdeYZw4VmsLuDL48CwT0CD8iEojPu25Wm/5n6T1N+LEVinQvaX0FZuOJ5OHq9E5o2yabpGKBDtFMf3EdzKQMI0dRulnVhXqMI1mcVUuLEIEXKgnr0ke1gwSo=,iv:7TFRW1ocjDzP9in4GOg+qEaSRTC6pNUhJfiJDT34H4s=,tag:UFQpjJgjpS/FRuzlIpm5Cg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
