---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "80.10.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1h0m0s
  
  targetNamespace: monitoring
  
  install:
    createNamespace: false
  
  values:
    kubelet:
      enabled: true
      serviceMonitor:
        https: true
        insecureSkipVerify: true

    prometheus-node-exporter:
      hostNetwork: true
      podSecurityPolicy:
        enabled: false

    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false

    grafana:
      admin:
        existingSecret: grafana-admin-credentials
        userKey: admin-user
        passwordKey: admin-password
      persistence:
        enabled: true
        type: pvc
        existingClaim: grafana-pvc
      service:
        type: LoadBalancer
        loadBalancerIP: "192.168.178.226"
        port: 80
      sidecar:
        datasources:
          enabled: true
          defaultDatasourceEnabled: true
      additionalDataSources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
          isDefault: true
          jsonData:
            timeout: 60
            timeInterval: 30s

    prometheus:
      prometheusSpec:
        retention: 10d

        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 0

        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: manual
              volumeName:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
