---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: n8n
spec:
  storageClassName: manual
  volumeName: n8n-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
