---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  namespace: postgres
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/mnt/data/postgres-pgadmin/pgadmin
