---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: postgres
spec:
  storageClassName: manual
  volumeName: pgadmin-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
