---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-pvc
  namespace: tailscale
spec:
  storageClassName: manual
  volumeName: tailscale-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
