apiVersion: ENC[AES256_GCM,data:7u8=,iv:eYFLkDUaBe8dm8HEx8kGb8yQUC6r1lSZRJjAwinfYHE=,tag:anSDxjNLDG5tmKYFiu5k2A==,type:str]
kind: ENC[AES256_GCM,data:+dmDgoLK,iv:0Ok/qVbTOt3Syz6tUc9tnnO9O1qAW3aHBfmYo/gHVvk=,tag:iCyOEmA/i1skTjbg6fF+iw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+SKVaOMEfxcXwa0S5WRHYeM=,iv:nEg0fFv4DHJuNTfQa+gvIxC+ubEVe0XBfcEW1oa97Ik=,tag:VNRXhHQmLFsHyIxn3p8fdw==,type:str]
    namespace: ENC[AES256_GCM,data:YJRY/mgQlIK3,iv:YQK2HspZ0SCpgH7KdR+JifOIT3M8E15bz4kf4tlohY0=,tag:cfpx59NSSYVlyLDgjNW1VA==,type:str]
type: ENC[AES256_GCM,data:oHncnEIf,iv:0ZTTakKUbkSapY6wA1hfQLSsXzXAg0sKxZu6ukjqNlI=,tag:xx42f84oc9OxrpsUI6RV/A==,type:str]
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:MGVoaS8nGAPpWSPkIJEzfeKWdriNy8DWeLfrXO/ODENxclWW3mIjPHHPuwZbIekp,iv:adnMAAa7EI5pjYuxik2JChyWDQC8z9JcT9evkyQ1Nm4=,tag:TjFMeOI4TFkTuqkzazxs6g==,type:str]
sops:
    age:
        - recipient: age1hj83fz2clp28q9sylkdpn50agz5z650nncl2c5g2xwgm6g6vxexqdjdecn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJV3hLb2U4N25kT2dPRDdW
            M0F3QmhGMjdMQmx3YkIrWDBOSEdSYzRSeGpZCi9rRlVYU0VRY1FTekJUZTM2YnIw
            MUVjVTM2Z0dXZGpHZmNDV2JZV2N1WDAKLS0tIG1ab0lkS0V5N0VRclUyVllrVnY0
            V0RoMzAvY1E5MVVUelZKeks5WlViUVkK+b+MW2SaRbVW2LghlAkIDUVqp52/wUx8
            V+aSQBP8t1Ytzta7wMKr2osZjbL63iXNYHTVX31ryNyP65smc3ZbSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T14:16:01Z"
    mac: ENC[AES256_GCM,data:y03Mg69OiUdzlz4FMjGTDpCqKj3hQiqViiOeKbemSrS4GldBqv6Fw2N36fOeeHO101zEl99SmaQQjl8Im0zMyqd5Hi/PA/+A/FTR66cuAGpNYSNdu/7zTvRqKwnoKanXQgVdZAlIh7rhH52vjcQNSu7SbA8coMIfrrg3RjDactw=,iv:qtMmu0sYFu54WehWGxxXs368sTAwTFp0grl4icJ9AxQ=,tag:HTg/Yi5lUaIzQlsciFnxSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
