apiVersion: ENC[AES256_GCM,data:7u8=,iv:eYFLkDUaBe8dm8HEx8kGb8yQUC6r1lSZRJjAwinfYHE=,tag:anSDxjNLDG5tmKYFiu5k2A==,type:str]
kind: ENC[AES256_GCM,data:+dmDgoLK,iv:0Ok/qVbTOt3Syz6tUc9tnnO9O1qAW3aHBfmYo/gHVvk=,tag:iCyOEmA/i1skTjbg6fF+iw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+SKVaOMEfxcXwa0S5WRHYeM=,iv:nEg0fFv4DHJuNTfQa+gvIxC+ubEVe0XBfcEW1oa97Ik=,tag:VNRXhHQmLFsHyIxn3p8fdw==,type:str]
    namespace: ENC[AES256_GCM,data:YJRY/mgQlIK3,iv:YQK2HspZ0SCpgH7KdR+JifOIT3M8E15bz4kf4tlohY0=,tag:cfpx59NSSYVlyLDgjNW1VA==,type:str]
type: ENC[AES256_GCM,data:oHncnEIf,iv:0ZTTakKUbkSapY6wA1hfQLSsXzXAg0sKxZu6ukjqNlI=,tag:xx42f84oc9OxrpsUI6RV/A==,type:str]
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:nx7GcYAPHByEIwRQHDfbacsNM9S+uv6I7T1zrCGcmXKkdolsu/fP5ZUH8KyTpzyM,iv:XWz1GVRu7PHDeJZCuaja/Orb0FwPFOrLBLJW07+YOCE=,tag:m4mvUmuSahPpPWy418CiWQ==,type:str]
sops:
    age:
        - recipient: age1hj83fz2clp28q9sylkdpn50agz5z650nncl2c5g2xwgm6g6vxexqdjdecn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJV3hLb2U4N25kT2dPRDdW
            M0F3QmhGMjdMQmx3YkIrWDBOSEdSYzRSeGpZCi9rRlVYU0VRY1FTekJUZTM2YnIw
            MUVjVTM2Z0dXZGpHZmNDV2JZV2N1WDAKLS0tIG1ab0lkS0V5N0VRclUyVllrVnY0
            V0RoMzAvY1E5MVVUelZKeks5WlViUVkK+b+MW2SaRbVW2LghlAkIDUVqp52/wUx8
            V+aSQBP8t1Ytzta7wMKr2osZjbL63iXNYHTVX31ryNyP65smc3ZbSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T11:47:59Z"
    mac: ENC[AES256_GCM,data:6zOyaCUYmRhUVNi4fURihyp4qMUcUfkOP6EBjc4E1m5gy3jvjABMNN5akk2D4Wk3RIeodPQk16qKPC4lIxNorhVDcNrWwea50e/KoiAHwWixBSBu8LqHEv+vcNwsGeArlKRl6/+vle5oGndqXewMh0Q9tImux6AvN+HJjfzOark=,iv:vFiH6ZhXno7Xt14WkuOZZgtniZTvgE7kRhoiT+NFK3g=,tag:W59ve2BtnYa+GmUCfCbm3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
