---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: npm-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/mnt/data/nginx-proxy-manager
