apiVersion: ENC[AES256_GCM,data:laE=,iv:K97XFiPRTpAzTWdgVfkZYZtATm/B+szHzcVxvQJQQd4=,tag:CJHeYaWG6nYVgh3WhY3cWg==,type:str]
kind: ENC[AES256_GCM,data:0wPfKARb,iv:Xj0cMNUIlnTfedlD7CTplZtYMab2X1h+lq0l1XaaZ/U=,tag:hzRv7P5jUuHS9m3HfBKNAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QsInjIILjE/GsaKneQ==,iv:rQ0QjEA/wAtlC1yjy6bfVSp7SZhTM/Ot35QgoLtFaOQ=,tag:AZ/7+VUXlBGF7tHV5Y2Hjw==,type:str]
    namespace: ENC[AES256_GCM,data:B7vJlrME,iv:KCs9iDL8TEgtLGjUpIcY/S//KE5i9MXCzfmkjsG+878=,tag:uCFYTlZw/RIgiTvA41waZw==,type:str]
type: ENC[AES256_GCM,data:HLTJJ/Ek,iv:t376xFizGUTH/UbB1iIgjXHF9MqBLTCPwxgnQHLRQrc=,tag:Z2WYpPlhFLLYygXzw0HHMw==,type:str]
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:aM4lHdBoA3g=,iv:1FGA0FjRXmqg2erq2asJIabmNaGklhfbjIfZBzpqkBw=,tag:2wREbT9OGhW7CfMAuMGg1A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:35TW8HjNgDb8RnYkH0+JHqvq0S0Jb40hgvNEGAgX2m9PVgLmq9ekQ42E1gUKigjrwg28QT5LnEcN//IrUcdMJg==,iv:L2TNFStvtAL/p3TjKoUDZtUkIWMqXM0PHQlDWqpkHco=,tag:bh5hpGJGnc4N7p196AS7WQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:3GzQYJCOng==,iv:/RkfJC7tHr7D1zUqOY7S3qdcTvGqRCd/s2Andnj7KqA=,tag:7O9OIWrjTNx9FU0eiWGc1w==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:vQhCU2ZaN29p70hLyzjZIwFYtRLdUR1w2SIdF8dlKlojB8x3WUKFTPNY7wvKW6Tg9VitwQVwZOWUgrTorATm1A==,iv:psRA1N5j7FfCqx5BmJ5iRXmm06eeD34BjphleJHzyl0=,tag:0/0vR3xRsrTnQD1S0q3Kcw==,type:str]
sops:
    age:
        - recipient: age1hj83fz2clp28q9sylkdpn50agz5z650nncl2c5g2xwgm6g6vxexqdjdecn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDd2hMRE04TjBJK29Pa0FW
            aFBNUU55VDVHT2hldUgxM2s1Nmo3dXhCUWdFCmhGRmsrbzFBeGViVnlOK0ZWZWtn
            ZExGNUFEdTVZcUl2MHByUjVVeHJWeUEKLS0tIGRxVFlvTXd0Qy9IazJTYkRqSnBu
            ZGg3WnpaRWZOL0JNS1N2a2N0dENNdmcK4p86Wd+Ffb4V6hcOd2z7mqB1mZI5m3l6
            Utjdi2rCrfB6X6ttAJ0Gvm8gFko4DQFTLC4Jju4g0alqUGES9k/4GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T09:56:37Z"
    mac: ENC[AES256_GCM,data:EZNV4RSEOGy0QrukBusPqWV1bGEFXGCyhSWGVQoO/RwpqgUXc283Mhlk5w0S/fwKnI1OAJVYhDyj+bTX2Y8Lt6wxySXGisuw1yOjhmnVeHnJrxsfGaqSX0rYwhlG8oMMf0VDTgZyNDJY5hi29si2OqUUdcF8XzLkOQZeGiQq8Fs=,iv:npY0SIKcmzQ+HSg9nebE9Banm6ZIPsqgUJZhzshbf38=,tag:NxyZ1jr9L1wYxFx6Hvg4/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
