apiVersion: ENC[AES256_GCM,data:j10=,iv:4iHzHTQmzyRjyFxpeRqpB7Jm3dLd5iBvmR1c9QLpHag=,tag:+nGVUmrNuZV7iYI+3dwscA==,type:str]
kind: ENC[AES256_GCM,data:3JW6CGAB,iv:WP9FDzJkTOF4TBJNBWM2aw2vRnXKWzxvet1daslmAj0=,tag:N4E7n4uq5YccL0zu5Y3tew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:q6FURL8cjeJEN9l4Reuq,iv:t4dwtfy8GOUKFIaA1hmeCyrFPl2FTOCDLeJEqn7WyYI=,tag:TFXZ3WX4CVWMpnBks57Q6Q==,type:str]
    namespace: ENC[AES256_GCM,data:gjd1AjehxTs=,iv:GdxlvwKV1iSR+ZrVWoVQiKvBv+kldsLI1SXfF0OoBlI=,tag:GlPzSyVmvl96Whh+AZ2Guw==,type:str]
type: ENC[AES256_GCM,data:22FyBaHF,iv:4/N3BLmH3OO5axg+jMGBWAhco1E3l5XCxO4aKjcCiTU=,tag:z2HgQ4+NmSaf0i4937wZag==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:P6ze+vC4tQ==,iv:V578uS62XeM/neCPqUC1JWgxmEsZqeHej4aY3Tce+lo=,tag:MPFSpjofPGdV9njFSUKmzA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:cyJrT38PmOQ=,iv:FFHJWsWsZbhhOet+Lf0cFYB+ecLNLdtTUfXMb77Xt7o=,tag:6qAGl+D0qo+CsNgBzO0W/Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:RgWWhv9FUT9XCv1SZmGl7p2GfqnJuNyndaURcV0VtDAoketuHczpwb0/J8JvAGxiOotLfCopNSNPKSo3WnJ8XA==,iv:8a8i0bnKDERlcLjubgZKn7XJo2SSe3A+xj+LOovHTK8=,tag:tA6pbOqmtSeoUISnhYhX5A==,type:str]
sops:
    age:
        - recipient: age1hj83fz2clp28q9sylkdpn50agz5z650nncl2c5g2xwgm6g6vxexqdjdecn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHS3ZpUTRXaGovWVZnSTY4
            ZFFISkpnc25LSTNLRzNWRU0vbzJLVWJ6ajFzCm5NSVA5NWV6OVhHL3U5TU1uY09J
            SnNrQUVJeUQ2aW1xTXdmSkNqSDBTbWsKLS0tIDk0SkZXb0FzQXlSM3dRY0lwVzRS
            N25lVmFsemdJWnJtOTNBMlRIb3JlL1EKc/ERIJp7hkwK+jrzDrKvQyZwZMNa9TH1
            94tbN01+G1XoA1pHPiwSR5MfXPGycaApfuL4BVx0XVOkeMBRrHYqDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T09:56:54Z"
    mac: ENC[AES256_GCM,data:7+99oT6SRijgexuXJzJr2cCapW9S4O5emI1DF3gVGe+FjeO5oytGrane2KtoL+FIx3sI0D6sqcZKD6wb/3MpQD7K9g0XofgqnQsfw/pylFKva7dsXQUxcLjHABKyiOYXPiNG5xMHPjEIIHBfjUrKq3kHRVC7gnSFLJk+fQyKMQk=,iv:pv5WM+0g9IyiPOfrDNwYa++kWWE3fkkcneXwTG9Xt2o=,tag:NF/61G2NvOHroXQK0XDVjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
