---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  namespace: pihole
spec:
  storageClassName: manual
  volumeName: pihole-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
