apiVersion: ENC[AES256_GCM,data:klU=,iv:G95albGetjvsLrkc2Fwprjdiy8o8lniqFRqyvGAyHfU=,tag:HdC4sQqmg8IPJdCp94UCJA==,type:str]
kind: ENC[AES256_GCM,data:NhZI2ODd,iv:+ng+cd9W6S9JfYdGjV9+D9zE85gqCS99uwk/31ZtH8A=,tag:nC175eJw8zn2rAOdwe2PrA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:X7dDVobrfn9etFNX,iv:FxFT5RtMRyf6wkkddDtU6gX60o3m5Oy3WLTrERto+Qg=,tag:izJ/JXxGeTrsjS5tlUr0IA==,type:str]
    namespace: ENC[AES256_GCM,data:rqYLohc=,iv:KdyGgsvqBSxalntNrFuardJ4ibnXXQ3J+kdRi+U1GUA=,tag:GsFer8Flid9CAzqygTgClw==,type:str]
type: ENC[AES256_GCM,data:r/pX+KlE,iv:w5JRbAQ9L649LK9BASGXih+gsy5m7rxYeggI6pm+eVc=,tag:/sVV6oOEJ65tMxdTSqW0Ng==,type:str]
stringData:
    rootUser: ENC[AES256_GCM,data:eBYCh82y2ec=,iv:PTPDeFCZ8TMYFOB/ckkyw1xPJkxCrICIwvobjaJ4JTM=,tag:5SqtTQt2OxPmCmY5hOuQSw==,type:str]
    rootPassword: ENC[AES256_GCM,data:YUtZwh0ZXPgDy04NQJ36G+1vwkjsyFOzzxVZEYFOXrXDH45PrtTzsEsl5hA5vVacYWk5VSY2fHQkQL2X8vsGUw==,iv:PfDtT+xY9OAO5OP2PWgdx/NH4qRcNxaWEDmiwNKPFRA=,tag:dblBv/yrcdCZMORIsSjSxg==,type:str]
sops:
    age:
        - recipient: age1hj83fz2clp28q9sylkdpn50agz5z650nncl2c5g2xwgm6g6vxexqdjdecn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NUl1eXQ5dUVsV0cwTWV1
            RklCaHE1NlErQjB4NzZaS1pLMUVwbFRDU21RCnk0SEFXSUoyUXhyMUZYcjRTZnVs
            a3ZwbG1majBLYkpCVHdua1Z0NkxEVGcKLS0tIGw2MUJaQVh1VzBrOHE3a0c4OGJw
            RXFlazYrMnFTN1ZPNG10WDc0UzJDQkUKPJdSOEfx+fRyrpmx99YY6QqzDJ7+QhVj
            ezsuMKkhgpwyanjSC0sUasfUpJ8nao8JQYRZaMSRmOYzrbWjyp/jPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T13:29:17Z"
    mac: ENC[AES256_GCM,data:xZHiW/S2pMHWWVXR0dexfLKJKGSduM42h8sPWKcqnK0BessK6BgAhnCOJ09/asznNkIqdOkRdrww39TP+IyeHQH2R+0plCVTk1+V7M1TM74NKPZRGTt4B612pVZRJIb2rQveOQQ0QQmDO7lWIpnhHMmijs/vU2BhBEgINq/fRmg=,iv:IkH4Xmz++GQi/yxc3GpWJ3bn9l08CDKKR0FKsw37NW4=,tag:YoFhpUsUdk9EYUwZiNfmyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
