---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-pvc
  namespace: actualbudget
spec:
  storageClassName: manual
  volumeName: actualbudget-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
